### ISSUE TITLE
Nested ants function gives error for long running fast for loops?

### ISSUE THREAD

**Issue by hiqsociety** [panjf2000/ants#153]
Getting error of 

2021/04/21 22:28:03 worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
2021/04/21 22:28:03 worker exits from panic: goroutine 23634 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1(0xc004b7ae70)
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.4/worker.go:58 +0x17c
panic(0x68dc60, 0x9d0eb0)
        /usr/lib/go-1.16/src/runtime/panic.go:965 +0x1b9

if nested multi layer. is this a problem?

**Comment by panjf2000** [comment]
Could you show me your code?

**Comment by panjf2000** [comment]
Closing this issue for inactivity.
