### ISSUE TITLE
死锁bug

### ISSUE THREAD

**Issue by lovelly** [panjf2000/ants#6]
func (p *Pool) getWorker() *Worker  这个函数的 199行 
必须先解锁在加锁， 要不然会产生死锁

	p.lock.Unlock()
		<-p.freeSignal
		p.lock.Lock()

**Comment by lovelly** [comment]
切片如下

9913 @ 0x42c73a 0x42c7ee 0x43cf64 0x43cc7d 0x46dfe8 0x7b28e0 0x7b2be5 0x4591f1
#	0x43cc7c	sync.runtime_SemacquireMutex+0x3c				E:/go/src/runtime/sema.go:71
#	0x46dfe7	sync.(*Mutex).Lock+0x107					E:/go/src/sync/mutex.go:134
#	0x7b28df	mp/vendor/github.com/panjf2000/ants.(*Pool).putWorker+0x6f	F:/gowork/src/mp/vendor/github.com/panjf2000/ants/pool.go:229
#	0x7b2be4	mp/vendor/github.com/panjf2000/ants.(*Worker).run.func1+0x54	F:/gowork/src/mp/vendor/github.com/panjf2000/ants/worker.go:53


1 @ 0x42c73a 0x42c7ee 0x404212 0x403ecb 0x7b27df 0x7b23e2 0x7f694a 0x7f68e1 0x4591f1
#	0x7b27de	mp/vendor/github.com/panjf2000/ants.(*Pool).getWorker+0x22e	F:/gowork/src/mp/vendor/github.com/panjf2000/ants/pool.go:199
#	0x7b23e1	mp/vendor/github.com/panjf2000/ants.(*Pool).Submit+0x61		F:/gowork/src/mp/vendor/github.com/panjf2000/ants/pool.go:125

**Comment by lovelly** [comment]
加了锁之后有下标溢出了。。。
panic: runtime error: index out of range

goroutine 7 [running]:
mp/vendor/github.com/panjf2000/ants.(*Pool).getWorker(0xc4200b6460, 0xc4202a6e01)
	F:/gowork/src/mp/vendor/github.com/panjf2000/ants/pool.go:213 +0x2ce
mp/vendor/github.com/panjf2000/ants.(*Pool).Submit(0xc4200b6460, 0xc4223d47d0, 0x0, 0x0)
	F:/gowork/src/mp/vendor/github.com/panjf2000/ants/pool.go:125 +0x62

**Comment by lovelly** [comment]
是最新的代码，我有添加一些print 所以行数不一样，这确实是一个bug 9913个协程阻塞在了 putWorker 很久很久。，。。。

**Comment by lovelly** [comment]
![image](https://user-images.githubusercontent.com/13118848/43630582-44f48000-9733-11e8-936d-9cb0d4145204.png)
 我idleWorkers 为空的， 但是我有n个协程阻塞在了 204行的	<-p.freeSignal， 这时候来了一个worker被放入idleWorkers， 很巧的是一个协程在putWorker结束锁后，在190行的p.lock.Lock()拿到了锁，这时候 n := len(idleWorkers) - 1 结果是0 这个协程很高兴的进入了e接下来的else分支, 然而不幸发生了，p.freeSignal的信号确被早已等在 204行的若干个协程中的一个拿走了， 那么 可怜的协程拿到了锁， 确无法等到 p.freeSignal 北京 p.freeSignal要拿到锁才能产生信号， 然后就。，。。

**Comment by panjf2000** [comment]
@lovelly 检查了一下，的确可能会有这个问题，周末会修复；
另外，我测试的时候试过1000w的量都没发现过这个问题，可能是我每个任务的执行时间太短了吧，所以我想问下你的任务量有多大以及每个人任务的耗时大概是多少？

**Comment by panjf2000** [comment]
@lovelly 应该已经修复了，可以再试试
