### ISSUE TITLE
goroutines num 一直上涨

### ISSUE THREAD

**Issue by weichangdong** [panjf2000/ants#99]
本地压测的话,压测的时候,goroutines 会上涨,但是压测结束后,会恢复.

go version 1.14.2
使用的 ants 版本是 v2.10(换了高版本v2.40 也有这个问题)

使用pprof `/debug/pprof/goroutine` 好多这样的文本
```
goroutine 25824 [chan receive, 21 minutes]:
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1(0xc0011fce70)
	/www/gopath1.14.2/pkg/mod/github.com/panjf2000/ants/v2@v2.1.0/worker_func.go:65 +0x74
created by github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run
	/www/gopath1.14.2/pkg/mod/github.com/panjf2000/ants/v2@v2.1.0/worker_func.go:49 +0x4c
```
核心的使用代码,每一个请求都会调用 DataQuery 这个函数.
```golang
func DataQuery(mobile, id, name string) DataQuerySkeleton {
	startTime := 123456789
	defer ants.Release()
	var wg sync.WaitGroup
	pUser, _ := ants.NewPoolWithFunc(50, func(para interface{}) {
		fun1(para)
		wg.Done()
	})
	defer pUser.Release()
	queryInputValue := map[string]string{
		TypeMobile: mobile,
		TypeId:    id,
		TypeName: name,
	}
	var inputUser = make(chan *GoroutineUserInputParaType, 3)

	for k, v := range queryInputValue {
		wg.Add(1)
		inPara := &GoroutineUserInputParaType{
			UinfoType: k,
			UinfoPara: v,
			StartTime: 123456789,
		}
		inputUser <- inPara
		pUser.Invoke(inputUser)
	}
	wg.Wait()
	close(inputUser)

	findInfo, minRegisterTime := func3(inputUser)
	totalUserNum := len(findInfo)
	queryInfo := DataQuerySkeleton{}

	if totalUserNum == 0 {
		return queryInfo
	}
	findOrdersStartTime := 423456789
	findUserUsedTime := findOrdersStartTime - startTime

	var inputOrder = make(chan *GoroutineOrderInputParaType, totalUserNum)

	pOrder, _ := ants.NewPoolWithFunc(50, func(para interface{}) {
		fun2(para)
		wg.Done()
	})
	defer pOrder.Release()
	for _, oneUser := range findInfo {
		wg.Add(1)
		inPara := &GoroutineOrderInputParaType{
			UinfoType: oneUser.Type,
			UinfoId:   oneUser.Uinfo.Id,
			StartTime: tools.GetUnixMillis(),
		}
		inputOrder <- inPara
		pOrder.Invoke(inputOrder)
	}
	wg.Wait()
	close(inputOrder)

    ......
	return queryInfo
}
```

**Comment by panjf2000** [comment]
1. ants.Release() 是释放内置的 pool，不需要每次都调用，你要是不想用内置 pool 直接调用一次就行；
2. 每次请求都要创建 pool，goroutine 数量多也很正常吧，一般来说这种 pool 应该搞成一个全局的，所有请求共享。

**Comment by weichangdong** [comment]
全局的话 试着放到init里面 貌似不行 而且全局的话 里面需要一个func
就算每次创建 不是有过期回收的机制么(本地压测貌似是这样的) 看grafada就是一直增长的.

**Comment by panjf2000** [comment]
> 全局的话 试着放到init里面 貌似不行 而且全局的话 里面需要一个func

你直接用那个不需要 func 的 pool 就行了

> 就算每次创建 不是有过期回收的机制么(本地压测貌似是这样的) 但是出问题的场景 线上 通过看grafada就是一直增长的 还有刷pprof 也是缓慢增长的 按道理夜里没请求了 也应该下降啊.

定时清理默认是清理超过十秒没有被使用过的 workers，还是说你自己重置了这个时间？你可以写个简单的 demo 测试一下，看看定时清理有没有生效，还是说有 bug？总之先测试一下吧。

**Comment by weichangdong** [comment]
谢谢了 我换那个不需要func的那个吧 
清理的 我没有自定义时间 默认的1秒吧
